---

  - name: 4.5.1 Check if the grub config file exists (Not Scored)
    stat: path=/etc/default/grub
    register: grub_cfg_file
    tags:
      - section4
      - section4.5

  - name: 4.5.2 Determines if AppArmor is set in grub config (Not Scored)
    command: "grep 'GRUB_CMDLINE_LINUX' /etc/default/grub"
    register: grub_apparmor
    changed_when: False
    when: grub_cfg_file.stat.exists
    always_run: True
    tags:
      - section4
      - section4.5

  - name: 4.5.3 Check if the extlinux config file exists (Not Scored)
    stat: path=/extlinux.conf
    register: extlinux_cfg_file
    tags:
      - section4
      - section4.5

